Help_Student/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'help_student.views.home', name='home'),
    url(r'^register/$', 'help_student.views.register', name='cadastro'),
    url(r'^matter/$', 'help_student.views.register_matter', name='materia'),
    url(r'^accounts/profile/$', 'help_student.views.profile', name='profile'),
    url(r'/status/$', 'help_student.views.status_matter', name='status'),
    url(r'^ranking/$', 'help_student.views.ranking', name='ranking'),
    (r'^accounts/login/$', 'django.contrib.auth.views.login',),
    url(r'^logout$', 'django.contrib.auth.views.logout_then_login', name='logout'),


    # url(r'^Help_Student/', include('Help_Student.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

help_student/models/matter.py
# -*- coding:utf-8 -*-
from django.db import models


class Matter(models.Model):
    nm_matter = models.CharField(u'Matéria', max_length=55)
    nr_difficulty = models.IntegerField('Dificuldade')

    class Meta:
        app_label = 'help_student'
        db_table = 'matter'
        verbose_name = u'Matéria'
        verbose_name_plural = u'Matérias'

    def __unicode__(self):
        return self.nm_matter

help_student/models/student_has_matter.py
# -*- coding:utf-8 -*-
from django.contrib.auth.models import User
from django.db import models
from help_student.models.matter import Matter

HELP_CHOICES = (
    (1, 'Preciso de ajuda'),
    (2, 'Posso ajudar'),
)

GOOD_NEWS = {
    'message': u'Bom dia %s,'
              u'\r o(a) estudante %s precisa de ajuda para estudar %s.'
              u'\r Você poderia adjuda-lo(la) com suas dúvidas?'
              u'\r aqui está o e-mail dele(a) para que possa entrar em contato: %s',
    'subject': u'[Help Student] Ajuar é sempre bom',
}

BAD_NEWS = {
    'message': u'Bom dia %s,'
            u'\r o(a) estudante %s pode lhe ajudar à estudar %s.'
              u'\r Você poderia pedir a sua ajuda e tirar suas dúvidas?'
              u'\r aqui está o e-mail dele(a) para que possa entrar em contato: %s',
    'subject': u'[Help Student] Não é vergonha alguma perdir ajuda',

}

class StudentHasMatter(models.Model):
    student = models.ForeignKey(User, verbose_name='Estudante')
    matter = models.ForeignKey(Matter, verbose_name=u'Matéria')
    nr_period = models.IntegerField('Ciclo')
    nr_record = models.IntegerField('Nota')
    tp_help = models.SmallIntegerField('Tipo de ajuda', choices=HELP_CHOICES, default=1)

    class Meta:
        app_label = 'help_student'
        db_table = 'student_has_matter'

    def __unicode__(self):
        return unicode(str(self.student.get_full_name()) + ' - ' + str(self.matter))

help_student/forms/matter.py
# -*- coding:utf-8 -*-
from django import forms


class MatterPeriodForm(forms.Form):
    nr_period = forms.IntegerField(label='Ciclo')

help_student/forms/student.py
# -*- coding:utf-8 -*-
from django import forms
from django.contrib.auth.models import User


class StudentProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super(StudentProfileForm, self).__init__(*args, **kwargs)

help_student/forms/student_has_matter.py
# -*- coding:utf-8 -*-
from django import forms
from help_student.models import Matter


class MatterRegisterForm(forms.ModelForm):
    matter = forms.ModelChoiceField(queryset=Matter.objects.all(), label=u'Matéria')
    nr_period = forms.IntegerField(label=u'Ciclo')
    nr_record = forms.IntegerField(label=u'Nota')

    class Meta:
        model = Matter
        fields = ('matter', 'nr_period', 'nr_record')

    def __init__(self, *args, **kwargs):
        super(MatterRegisterForm, self).__init__(*args, **kwargs)


class RankingForm(forms.ModelForm):
    matter = forms.ModelChoiceField(queryset=Matter.objects.all(), label=u'Matéria', required=False)
    nr_period = forms.IntegerField(label=u'Ciclo', required=False)

    class Meta:
        model = Matter
        fields = ('matter', 'nr_period')

    def __init__(self, *args, **kwargs):
        super(RankingForm, self).__init__(*args, **kwargs)

help_student/views.py
# -*- coding:utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.views.generic.simple import direct_to_template
from help_student.forms.matter import MatterPeriodForm
from help_student.forms.student import StudentProfileForm
from help_student.forms.student_has_matter import MatterRegisterForm, RankingForm
from help_student.models import StudentHasMatter


def home(request):
    return direct_to_template(request, 'base.html',)


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect('../accounts/profile')
    else:
        form = UserCreationForm()
    return direct_to_template(request, 'register_form.html', {'form': form, 'legend': 'Cadastro'})

@login_required()
def profile(request):
    if request.method == 'POST':
        form = StudentProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
        return direct_to_template(request, 'register_form.html', {'form': form, 'message': 'Aterado com Sucesso', 'legend': 'Perfil'})
    else:
        form = StudentProfileForm(instance=request.user)
    return direct_to_template(request, 'register_form.html', {'form': form, 'legend': 'Perfil'})

@login_required()
def register_matter(request):
    if request.method == 'POST':
        form = MatterRegisterForm(request.POST)
        message = ''
        if form.is_valid():
            if form.cleaned_data['nr_record'] >= 60:
                tp_help = 2
            else:
                tp_help = 1
            nr_record = form.cleaned_data['nr_record']
            nr_period = form.cleaned_data['nr_period']

            student_matter, has_matter = StudentHasMatter.objects.get_or_create(
                student=request.user,
                matter=form.cleaned_data['matter'], defaults={'nr_record': nr_record, 'nr_period': nr_period})

            student_matter.nr_record = nr_record
            student_matter.nr_period = nr_period
            student_matter.tp_help = tp_help
            student_matter.save()

            if has_matter:
                message = u'Matéria criada com sucesso'
            else:
                message = u'Matéria editada com sucesso'

        return direct_to_template(request, 'register_form.html', {'form': form, 'message': message, 'legend': u'Registrar Matéria'})

    else:
        form = MatterRegisterForm()

    return direct_to_template(request, 'register_form.html', {'form': form, 'legend': u'Registrar Matéria'})


@login_required
def status_matter(request):
    student = StudentHasMatter.objects.filter(student=request.user).order_by('nr_period', '-nr_record')
    if request.POST:
        form = MatterPeriodForm(request.POST)
        if form.is_valid():
            student = student.filter(nr_period=form.cleaned_data["nr_period"])
    else:
        form = MatterPeriodForm()

    return direct_to_template(request, 'status_matter.html', {'info': student, 'form': form})


@login_required()
def ranking(request):

    if request.POST:
        form = RankingForm(request.POST)
        if form.is_valid():
            period = form.cleaned_data["nr_period"]
            matter = form.cleaned_data["matter"]
            if period and matter:
                student = StudentHasMatter.objects.filter(nr_period=period, matter=matter,)
            elif period:
                student = StudentHasMatter.objects.filter(nr_period=period)
            elif matter:
                student = StudentHasMatter.objects.filter(matter=matter)
            else:
                student = StudentHasMatter.objects.all()
            student = make_avg(student)

    else:
        form = RankingForm()
        student = StudentHasMatter.objects.all()
        student = make_avg(student)

    return direct_to_template(request, 'ranking.html', {'infos': student, 'form': form, })


def make_avg(students):
    student_list = list()
    for student in students:
        new_record = 0
        records = students.filter(student_id=student.student.id).values('nr_record')
        if records:
            for record in records:
                new_record += record['nr_record']
            new_record = new_record / len(records)
            new = {'student': student.student.get_full_name(), 'record': new_record}
            if new not in student_list:
                student_list.append(new)

    student_list.sort(reverse=True)
    return student_list[:10]

help_student/templates/base.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="utf-8">
    <title>{% block title %}Help Student{% endblock %}</title>
    <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/bootstrap.css"/>
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/style.css"/>
    {% block extra_head %}{% endblock %}
</head>
<body class="tab-content">

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="/">Home</a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li class="">
                        <a href="/matter/status/">Matérias</a>
                    </li>
                    <li class="">
                        <a href="/accounts/profile/">Perfil</a>
                    </li>
                    <li class="">
                        <a href="/ranking">Ranking</a>
                    </li>
                    <li class="">
                        <a href="../..{% url logout %}">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">

    </div>

</div>
<div class="container">
    <hr>
    <h1>Help Student</h1>
    <p class="lead">Criado para melhor interação de estudantes e principalmente ajudar nos estudos</p>


{% block content %} {% endblock content %}

</div>
</body>
</html>

help_student/templates/profile_edit.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="well">
            <form class="form-horizontal" action="" method="POST">
                {% csrf_token %}
                <fieldset>
                    <legend>Perfil</legend>
                    {{ form.errors }}
                    {{ message }}
                    <div class="control-group">
                        <label class="control-label" >{{ form.username.label_tag }}</label>
                        {{ form.username }}
                        {{ form.username.error_messages }}
                    </div>
                    <div class="control-group">
                        <label class="control-label" >{{ form.first_name.label_tag }}</label>
                        {{ form.first_name }}
                        {{ form.first_name.error_messages }}
                    </div>
                    <div class="control-group">
                        <label class="control-label" >{{ form.last_name.label_tag }}</label>
                        {{ form.last_name }}
                        {{ form.last_name.error_messages }}
                    </div>
                    <div class="control-group">
                        <label class="control-label" >{{ form.email.label_tag }}</label>
                        {{ form.email }}
                        {{ form.email.error_messages }}
                    </div>
                    <div class="control-group">
                        <div class="controls">
                            <input type="submit" class="btn btn-success" value="Editar">
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
{% endblock content %}

help_student/templates/ranking.html
{% extends 'base.html' %}
{% block content %}
    <form class="form-horizontal" action="" method="POST">
        {% csrf_token %}
        <div class="control-group">
            <div class="controls">
                {{ form }}
                <input type="submit" class="btn btn-success" value="Mudar">
            </div>
        </div>
    </form>

    <table class="table">
        <tbody>
        <tr>
            <td class="span3"></td>
            <td class="span3">Estudante</td>
            <td>Média</td>
        </tr>
        {% for info in infos %}
            <tr>
                <td></td>
                <td>{{ info.student }}</td>
                <td>{{ info.record }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

help_student/templates/register_form.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="well">
            <form class="form-horizontal" action="." method="POST">
                {% csrf_token %}
                <fieldset>
                    <legend>{{ legend }}</legend>
                    {{ message }}
                    {% for fields in form %}
                        {{ fields.erros }}
                        <div class="{% if fields.errors %}alert-error{% endif %}">
                        <div class="control-group">
                            <label class="control-label" for="{{ fields.label }}">{{ fields.label }}:</label>
                            {{ fields }}
                            <div class="controls">
                                {{ fields.errors }}
                            </div>
                        </div>
                        </div>
                    {% endfor %}
                    <div class="control-group">
                        <div class="controls">
                            <input type="submit" class="btn btn-success" value="{% if legend == 'Cadastro' %}Cadastrar {% else %}Salvar{% endif %}">
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
{% endblock content %}

help_student/templates/status_matter.html
{% extends 'base.html' %}
{% block content %}
    <form class="form-horizontal" action="" method="POST">
        {% csrf_token %}
        <div class="control-group">
            <div class="{% if form.errors %}alert-error{% endif %}">
            <div class="controls ">
                {{ form }}
                <input type="submit" class="btn btn-success" value="Filtrar">
                <a href="/matter"><input type="button" class="btn btn-success" value="Cadastrar Matéria"></a>
            </div>
            </div>
        </div>
    </form>

    <table class="table">
    <tbody>
        <tr>
            <td class="span3"></td>
            <td>Matéria</td>
            <td>Nota</td>
            <td>Estado</td>
        </tr>
        {% for infos in info %}
            <tr{% if infos.nr_record < 60 %} class="warning" {% endif %}>
                <td></td>
                <td>{{ infos.matter }}</td>
                <td>{{ infos.nr_record }}</td>
                <td>{{ infos.get_tp_help_display }}</td>
            </tr>
        {% endfor %}
    </tbody>
    </table>
{% endblock content %}